.TH "GumboNode" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGumboNodeType\fP \fBtype\fP"
.br
.ti -1c
.RI "GumboNode * \fBparent\fP"
.br
.ti -1c
.RI "size_t \fBindex_within_parent\fP"
.br
.ti -1c
.RI "\fBGumboParseFlags\fP \fBparse_flags\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBGumboDocument\fP \fBdocument\fP"
.br
.ti -1c
.RI "   \fBGumboElement\fP \fBelement\fP"
.br
.ti -1c
.RI "   \fBGumboText\fP \fBtext\fP"
.br
.ti -1c
.RI "} \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A supertype for \fBGumboElement\fP and \fBGumboText\fP, so that we can include one generic type in lists of children and cast as necessary to subtypes\&.
.PP
Forward declaration of GumboNode so it can be used recursively in GumboNode\&.parent\&. 
.SH "Field Documentation"
.PP 
.SS "\fBGumboNodeType\fP GumboNode::type"The type of node that this is\&. 
.SS "GumboNode* GumboNode::parent"Pointer back to parent node\&. Not owned\&. 
.SS "size_t GumboNode::index_within_parent"The index within the parent's children vector of this node\&. 
.SS "\fBGumboParseFlags\fP GumboNode::parse_flags"A bitvector of flags containing information about why this element was inserted into the parse tree, including a variety of special parse situations\&. 
.SS "union { \&.\&.\&. }   GumboNode::v"The actual node data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
