.TH "GumboDocument" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboDocument \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGumboVector\fP \fBchildren\fP"
.br
.ti -1c
.RI "bool \fBhas_doctype\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBpublic_identifier\fP"
.br
.ti -1c
.RI "const char * \fBsystem_identifier\fP"
.br
.ti -1c
.RI "\fBGumboQuirksModeEnum\fP \fBdoc_type_quirks_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information specific to document nodes\&. 
.SH "Field Documentation"
.PP 
.SS "\fBGumboVector\fP \fBGumboDocument::children\fP"An array of GumboNodes, containing the children of this element\&. This will normally consist of the <html> element and any comment nodes found\&. Pointers are owned\&. 
.SS "\fBGumboQuirksModeEnum\fP \fBGumboDocument::doc_type_quirks_mode\fP"Whether or not the document is in QuirksMode, as determined by the values in the GumboTokenDocType template\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
