.TH "GumboOutput" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GumboNode * \fBdocument\fP"
.br
.ti -1c
.RI "GumboNode * \fBroot\fP"
.br
.ti -1c
.RI "\fBGumboVector\fP \fBerrors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The output struct containing the results of the parse\&. 
.SH "Field Documentation"
.PP 
.SS "GumboNode* \fBGumboOutput::document\fP"Pointer to the document node\&. This is a GumboNode of type NODE_DOCUMENT that contains the entire document as its child\&. 
.SS "GumboNode* \fBGumboOutput::root\fP"Pointer to the root node\&. This the <html> tag that forms the root of the document\&. 
.SS "\fBGumboVector\fP \fBGumboOutput::errors\fP"A list of errors that occurred during the parse\&. NOTE: In version 1\&.0 of this library, the API for errors hasn't been fully fleshed out and may change in the future\&. For this reason, the GumboError header isn't part of the public API\&. Contact us if you need errors reported so we can work out something appropriate for your use-case\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
