.TH "GumboAttribute" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGumboAttributeNamespaceEnum\fP \fBattr_namespace\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBGumboStringPiece\fP \fBoriginal_name\fP"
.br
.ti -1c
.RI "const char * \fBvalue\fP"
.br
.ti -1c
.RI "\fBGumboStringPiece\fP \fBoriginal_value\fP"
.br
.ti -1c
.RI "\fBGumboSourcePosition\fP \fBname_start\fP"
.br
.ti -1c
.RI "\fBGumboSourcePosition\fP \fBname_end\fP"
.br
.ti -1c
.RI "\fBGumboSourcePosition\fP \fBvalue_start\fP"
.br
.ti -1c
.RI "\fBGumboSourcePosition\fP \fBvalue_end\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a single attribute on an HTML tag\&. This is a name-value pair, but also includes information about source locations and original source text\&. 
.SH "Field Documentation"
.PP 
.SS "\fBGumboAttributeNamespaceEnum\fP \fBGumboAttribute::attr_namespace\fP"The namespace for the attribute\&. This will usually be GUMBO_ATTR_NAMESPACE_NONE, but some XLink/XMLNS/XML attributes take special values, per: http://www.whatwg.org/specs/web-apps/current-work/multipage/tree-construction.html#adjust-foreign-attributes 
.SS "const char* \fBGumboAttribute::name\fP"The name of the attribute\&. This is in a freshly-allocated buffer to deal with case-normalization, and is null-terminated\&. 
.SS "\fBGumboStringPiece\fP \fBGumboAttribute::original_name\fP"The original text of the attribute name, as a pointer into the original source buffer\&. 
.SS "const char* \fBGumboAttribute::value\fP"The value of the attribute\&. This is in a freshly-allocated buffer to deal with unescaping, and is null-terminated\&. It does not include any quotes that surround the attribute\&. If the attribute has no value (for example, 'selected' on a checkbox), this will be an empty string\&. 
.SS "\fBGumboStringPiece\fP \fBGumboAttribute::original_value\fP"The original text of the value of the attribute\&. This points into the original source buffer\&. It includes any quotes that surround the attribute, and you can look at original_value\&.data[0] and original_value\&.data[original_value\&.length - 1] to determine what the quote characters were\&. If the attribute has no value, this will be a 0-length string\&. 
.SS "\fBGumboSourcePosition\fP \fBGumboAttribute::name_start\fP"The starting position of the attribute name\&. 
.SS "\fBGumboSourcePosition\fP \fBGumboAttribute::name_end\fP"The ending position of the attribute name\&. This is not always derivable from the starting position of the value because of the possibility of whitespace around the = sign\&. 
.SS "\fBGumboSourcePosition\fP \fBGumboAttribute::value_start\fP"The starting position of the attribute value\&. 
.SS "\fBGumboSourcePosition\fP \fBGumboAttribute::value_end\fP"The ending position of the attribute value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
