.TH "GumboText" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboText \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBtext\fP"
.br
.ti -1c
.RI "\fBGumboStringPiece\fP \fBoriginal_text\fP"
.br
.ti -1c
.RI "\fBGumboSourcePosition\fP \fBstart_pos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The struct used to represent TEXT, CDATA, COMMENT, and WHITESPACE elements\&. This contains just a block of text and its position\&. 
.SH "Field Documentation"
.PP 
.SS "const char* \fBGumboText::text\fP"The text of this node, after entities have been parsed and decoded\&. For comment/cdata nodes, this does not include the comment delimiters\&. 
.SS "\fBGumboStringPiece\fP \fBGumboText::original_text\fP"The original text of this node, as a pointer into the original buffer\&. For comment/cdata nodes, this includes the comment delimiters\&. 
.SS "\fBGumboSourcePosition\fP \fBGumboText::start_pos\fP"The starting position of this node\&. This corresponds to the position of original_text, before entities are decoded\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
