.TH "GumboSourcePosition" 3 "Tue Aug 13 2013" "Version 0.9.0" "Gumbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GumboSourcePosition \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gumbo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBline\fP"
.br
.ti -1c
.RI "unsigned int \fBcolumn\fP"
.br
.ti -1c
.RI "unsigned int \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a character position within the original text buffer\&. Line and column numbers are 1-based and offsets are 0-based, which matches how most editors and command-line tools work\&. Also, columns measure positions in terms of characters while offsets measure by bytes; this is because the offset field is often used to pull out a particular region of text (which in most languages that bind to C implies pointer arithmetic on a buffer of bytes), while the column field is often used to reference a particular column on a printable display, which nowadays is usually UTF-8\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Gumbo from the source code\&.
